name: test SQL Server

on:
  push: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: "Installing packages"
        run: | 
          pip install wheel
          pip install setuptools
          pip install pandas
          pip install pyodbc
      
      - name: "Running SQL Express"
        run : |
          docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=MyPass@word" -e "MSSQL_PID=Express" -p 1433:1433 -d --name=sql mcr.microsoft.com/mssql/server:2019-latest

      - name: "Running main.py"
        run : |
          python -m main.py

          